// Generated by Apple Swift version 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if __has_feature(modules)
@import CoreData;
@import CoreLocation;
@import Foundation;
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="PWEngagement",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class NSEntityDescription;
@class NSManagedObjectContext;

SWIFT_CLASS("_TtC12PWEngagement18BeaconBundleEntity")
@interface BeaconBundleEntity : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class BeaconCampaignEntity;
@class NSSet;

@interface BeaconBundleEntity (SWIFT_EXTENSION(PWEngagement))
- (void)addCampaignsObject:(BeaconCampaignEntity * _Nonnull)value;
- (void)removeCampaignsObject:(BeaconCampaignEntity * _Nonnull)value;
- (void)addCampaigns:(NSSet * _Nonnull)values;
- (void)removeCampaigns:(NSSet * _Nonnull)values;
@end




@interface BeaconBundleEntity (SWIFT_EXTENSION(PWEngagement))
@property (nonatomic, copy) NSString * _Nullable bundleType;
@property (nonatomic, copy) NSDate * _Nullable expirationDate;
@property (nonatomic) int64_t formatVersion;
@property (nonatomic, copy) NSString * _Nullable identifier;
@property (nonatomic) BOOL isMonitored;
@property (nonatomic, copy) NSString * _Nullable organizationName;
@property (nonatomic, copy) NSDate * _Nullable relevanceDate;
@property (nonatomic, copy) NSString * _Nullable serialNumber;
@property (nonatomic, copy) NSString * _Nullable summary;
@property (nonatomic, copy) NSString * _Nullable vbleSdkToken;
@property (nonatomic, strong) NSSet * _Nullable campaigns;
@end


SWIFT_CLASS("_TtC12PWEngagement26BeaconCampaignActionEntity")
@interface BeaconCampaignActionEntity : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface BeaconCampaignActionEntity (SWIFT_EXTENSION(PWEngagement))
@property (nonatomic, copy) NSString * _Nullable actionHtml;
@property (nonatomic, copy) NSString * _Nullable actionTitle;
@property (nonatomic, strong) BeaconCampaignEntity * _Nullable campaign;
@end


SWIFT_CLASS("_TtC12PWEngagement20BeaconCampaignEntity")
@interface BeaconCampaignEntity : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@class BeaconEntity;

@interface BeaconCampaignEntity (SWIFT_EXTENSION(PWEngagement))
- (void)addBeaconsInsideObject:(BeaconEntity * _Nonnull)value;
- (void)removeBeaconsInsideObject:(BeaconEntity * _Nonnull)value;
- (void)addBeaconsInside:(NSSet * _Nonnull)values;
- (void)removeBeaconsInside:(NSSet * _Nonnull)values;
@end

@class BeaconCampaignMetadataEntity;

@interface BeaconCampaignEntity (SWIFT_EXTENSION(PWEngagement))
- (void)addMetadataObject:(BeaconCampaignMetadataEntity * _Nonnull)value;
- (void)removeMetadataObject:(BeaconCampaignMetadataEntity * _Nonnull)value;
- (void)addMetadata:(NSSet * _Nonnull)values;
- (void)removeMetadata:(NSSet * _Nonnull)values;
@end


@interface BeaconCampaignEntity (SWIFT_EXTENSION(PWEngagement))
- (void)addBeaconsObject:(BeaconEntity * _Nonnull)value;
- (void)removeBeaconsObject:(BeaconEntity * _Nonnull)value;
- (void)addBeacons:(NSSet * _Nonnull)values;
- (void)removeBeacons:(NSSet * _Nonnull)values;
@end


@interface BeaconCampaignEntity (SWIFT_EXTENSION(PWEngagement))
- (void)addActionsObject:(BeaconCampaignActionEntity * _Nonnull)value;
- (void)removeActionsObject:(BeaconCampaignActionEntity * _Nonnull)value;
- (void)addActions:(NSSet * _Nonnull)values;
- (void)removeActions:(NSSet * _Nonnull)values;
@end




@interface BeaconCampaignEntity (SWIFT_EXTENSION(PWEngagement))
@property (nonatomic, copy) NSString * _Nullable campaignType;
@property (nonatomic, copy) NSDate * _Nullable expirationDate;
@property (nonatomic, copy) NSString * _Nullable identifier;
@property (nonatomic, copy) NSDate * _Nullable lastFiredDate;
@property (nonatomic, copy) NSString * _Nullable notificationMessage;
@property (nonatomic, copy) NSString * _Nullable notificationTitle;
@property (nonatomic, copy) NSString * _Nullable proximity;
@property (nonatomic, copy) NSString * _Nullable proximityType;
@property (nonatomic, copy) NSDate * _Nullable relevanceDate;
@property (nonatomic) int64_t repeatInterval;
@property (nonatomic, strong) NSSet * _Nullable actions;
@property (nonatomic, strong) NSSet * _Nullable beacons;
@property (nonatomic, strong) NSSet * _Nullable beaconsInside;
@property (nonatomic, strong) BeaconBundleEntity * _Nullable bundle;
@property (nonatomic, strong) NSSet * _Nullable metadata;
@end


SWIFT_CLASS("_TtC12PWEngagement28BeaconCampaignMetadataEntity")
@interface BeaconCampaignMetadataEntity : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface BeaconCampaignMetadataEntity (SWIFT_EXTENSION(PWEngagement))
@property (nonatomic, copy) NSString * _Nullable key;
@property (nonatomic, copy) NSString * _Nullable value;
@property (nonatomic, strong) BeaconCampaignEntity * _Nullable campaign;
@end


SWIFT_CLASS("_TtC12PWEngagement12BeaconEntity")
@interface BeaconEntity : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface BeaconEntity (SWIFT_EXTENSION(PWEngagement))
- (void)addCampaignsObject:(BeaconCampaignEntity * _Nonnull)value;
- (void)removeCampaignsObject:(BeaconCampaignEntity * _Nonnull)value;
- (void)addCampaigns:(NSSet * _Nonnull)values;
- (void)removeCampaigns:(NSSet * _Nonnull)values;
@end


@interface BeaconEntity (SWIFT_EXTENSION(PWEngagement))
- (void)addInsideCampaignsObject:(BeaconCampaignEntity * _Nonnull)value;
- (void)removeInsideCampaignsObject:(BeaconCampaignEntity * _Nonnull)value;
- (void)addInsideCampaigns:(NSSet * _Nonnull)values;
- (void)removeInsideCampaigns:(NSSet * _Nonnull)values;
@end


@interface BeaconEntity (SWIFT_EXTENSION(PWEngagement))
@property (nonatomic, copy) NSString * _Nullable identifier;
@property (nonatomic) int64_t interval;
@property (nonatomic) BOOL isVble;
@property (nonatomic) int64_t major;
@property (nonatomic) int64_t minor;
@property (nonatomic, copy) NSString * _Nullable summary;
@property (nonatomic) int64_t txPower;
@property (nonatomic, copy) NSString * _Nullable uuid;
@property (nonatomic, strong) NSSet * _Nullable campaigns;
@property (nonatomic, strong) NSSet * _Nullable insideCampaigns;
@end








SWIFT_CLASS("_TtC12PWEngagement10Engagement")
@interface Engagement : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end








SWIFT_CLASS("_TtC12PWEngagement14GeofenceEntity")
@interface GeofenceEntity : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end







@class LocationEntity;

@interface GeofenceEntity (SWIFT_EXTENSION(PWEngagement))
@property (nonatomic) BOOL allowCheckIn;
@property (nonatomic, copy) NSString * _Nullable code;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable eventTypes;
@property (nonatomic) int64_t id;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic) double radius;
@property (nonatomic) int64_t state;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable tags;
@property (nonatomic, strong) LocationEntity * _Nullable location;
@end


SWIFT_CLASS("_TtC12PWEngagement14LocationEntity")
@interface LocationEntity : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface LocationEntity (SWIFT_EXTENSION(PWEngagement))
@property (nonatomic) double latitude;
@property (nonatomic) double longitude;
@property (nonatomic, strong) GeofenceEntity * _Nullable geofence;
@end


SWIFT_CLASS("_TtC12PWEngagement13MessageEntity")
@interface MessageEntity : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end






@interface MessageEntity (SWIFT_EXTENSION(PWEngagement))
@property (nonatomic, copy) NSString * _Nullable body;
@property (nonatomic, copy) NSString * _Nullable campaignType;
@property (nonatomic) int64_t id;
@property (nonatomic, copy) NSDictionary<NSString *, NSString *> * _Nullable metadata;
@property (nonatomic, copy) NSString * _Nullable promotionBody;
@property (nonatomic, copy) NSString * _Nullable promotionTitle;
@property (nonatomic) BOOL read;
@property (nonatomic, copy) NSDate * _Nullable timestamp;
@property (nonatomic, copy) NSString * _Nullable title;
@end



#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
