// Objective-C API for talking to github.com/mistsys/location/mobile Go package.
//   gobind -lang=objc github.com/mistsys/location/mobile
//
// File is generated by gobind. Do not edit.

#ifndef __Mobile_H__
#define __Mobile_H__

@import Foundation;
#include "Universe.objc.h"


@interface Mobile : NSObject
// skipped variable BMap with unsupported type: *types.Named

// skipped variable MyMap with unsupported type: *types.Named

// skipped variable MyState with unsupported type: *types.Named

// skipped variable PMap with unsupported type: *types.Named

// skipped variable SnapHeadings with unsupported type: *types.Slice

// skipped variable TsMap with unsupported type: *types.Named

@end

FOUNDATION_EXPORT void MobileClearWayfindingPath(void);

// skipped function DeadReckonRequest with unsupported parameter or return types


FOUNDATION_EXPORT BOOL MobileDetectMotion(NSData* clientReqeustJson);

FOUNDATION_EXPORT double MobileGetCompassOffset(void);

FOUNDATION_EXPORT NSData* MobileGetLocationEstimate(NSData* inEpRequestJson);

// skipped function GetMap with unsupported parameter or return types


FOUNDATION_EXPORT NSString* MobileGetMapId(NSData* epRequestJson);

FOUNDATION_EXPORT double MobileGetNorthOffset(void);

FOUNDATION_EXPORT BOOL MobileGetUseLE(void);

FOUNDATION_EXPORT void MobileInitializeDR(void);

// skipped function Motion with unsupported parameter or return types


FOUNDATION_EXPORT void MobileSetUseLE(BOOL useLE);

FOUNDATION_EXPORT void MobileStoreEpResponse(NSData* inEpResponse);

FOUNDATION_EXPORT BOOL MobileStoreMapInfo(NSData* mapInfoJson);

FOUNDATION_EXPORT BOOL MobileStoreOneMapInfo(NSData* mapInfoJson);

FOUNDATION_EXPORT BOOL MobileStoreSiteDevices(NSData* deviceInfoJson);

FOUNDATION_EXPORT void MobileStoreWayfindingPath(NSData* wayPath);

#endif
